// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
}
